#!/bin/bash -eux
function main() {
  local scripts_dir
  scripts_dir=$(cd "$(dirname "${0}")" && pwd)

  local root_dir
  root_dir=$(cd "${scripts_dir}/.." && pwd)

  export GO15VENDOREXPERIMENT=1
  export PATH="${root_dir}/bin:${PATH}"
  go get github.com/onsi/ginkgo/ginkgo
  dep ensure

  ginkgo \
  -v \
    -r \
    -race \
    -failFast \
    -succinct \
    -randomizeAllSpecs \
    -randomizeSuites \
    -slowSpecThreshold 300 \
    "$@"
}

main "$@"
